### ISSUE TITLE
(Hub 1.2.001) Can't access hub

### ISSUE THREAD

**Issue by GoncaloEsi** [CorefluxCommunity/Coreflux-hub#1]
### Describe the bug 🐞

Before anything, let me clarify I have previously installed this Coreflux version successfully on another computer. It was a clean Windows 11 installation and I had admin rights. This computer is now running Coreflux with an S7 asset successfully.

Now regarding this problem: I wanted to upgrade Coreflux to the newest hub on my work computer for which only the IT guy has the admin credentials. I really only use Coreflux on this computer to run the Mqtt broker locally (no other assets) and develop Unity 3D apps that communicate with it. I was doing that up until now with the 1.0.5 Hub and the MqttBroker asset.

I uninstalled Coreflux 1.0.5 from the computer (Control panel -> Uninstall a program). The IT guy had to put his admin password. Then, I ran the new 1.2.001 CorefluxHub.exe (IT guy had to insert password again, the executable runs as admin) and the Hub opened up.
I installed a central before logging in (Installs -> Install New Central -> Install Coreflux Version 1.2.8 (64-bit)). When asked for an ID, I called it "coreflux". I can see that name on the Windows services list, not running, with startup type as "Manual".
Then, I actually logged in to the Coreflux account.
But now, the "Hub Access" tab keeps trying to load undefinitely, and even when I try to login to the Hub with the root/coreflux credentials, it fails to login.
The Mqtt broker (127.0.0.1:1883) is also not running, I can't access it using Mqtt Explorer.

![Captura de ecrã 2023-11-08 113711](https://github.com/CorefluxCommunity/Coreflux-hub/assets/134688998/62cd71bf-cfe4-468e-8e81-5eae49eee4c8)
![Captura de ecrã 2023-11-08 113840](https://github.com/CorefluxCommunity/Coreflux-hub/assets/134688998/c36f620b-4f13-420e-982d-60c035e22e01)
![Captura de ecrã 2023-11-08 114014](https://github.com/CorefluxCommunity/Coreflux-hub/assets/134688998/4bd40e98-8de9-4b73-b853-e621d4e49373)
![doesnotload](https://github.com/CorefluxCommunity/Coreflux-hub/assets/134688998/113b84a5-1fd6-42e3-b5ed-1902d44ef094)

### Steps to Reproduce 🔄

On a windows 11 user without admin rights:

- Uninstall Coreflux 1.0.5
- Open the new 1.2.001 CorefluxHub.exe
- Install a new Central on 127.0.0.1:1883 (let's call it "coreflux" as the ID)
- Login to Coreflux account
- Try to open the "Hub Access" page (unsuccessfully)
- Try to login to the Data Hub, using "coreflux" as the data hub name, 127.0.0.1, port 1883, and default root/coreflux user and password (unsuccessfully)

### Expected behavior ✅

I should be able to login to the Coreflux hub with root/coreflux.

### Environment 🌐

Windows 11

### Terms of Service

- [X] I agree

**Comment by Jogana3** [comment]
Hi, can you check if the error still happens in HUB last version that has been uploaded?

**Comment by GoncaloEsi** [comment]
Hi. You mean 1.2.004 right? I will try and let you know here. Is it ok if I login to the corefluz account and only after install a new central, or do you want me to do that in the same order I presented on the bug description?

**Comment by Jogana3** [comment]
Yes in 1.2.004 version, try to do it in the same order as the description to see if the same happens. Let me know if the issue it's still there.

**Comment by GoncaloEsi** [comment]
Hi again, me and the IT guy have managed to make it work. Let me clarify:

When I did the exact same thing as described in the bug, but with version 1.2.004, the only difference was that the "Hub Access" tab actually did load. But everything else was the same.

What we did was delete folders/files that we believe were lingering from the previous 1.0.5 installation, on C:\ProgramData\Coreflux

After that, we deleted C:\Users\Administrador\AppData\Roaming\corefluxhub and installed a new central from the GUI, which I was successfully able to login with root/coreflux

**Comment by HugoAVaz** [comment]
Should an update feature fix this?

**Comment by GoncaloEsi** [comment]
Hey Hugo, I think that maybe only people that go through what I did (uninstall the last and install the newest Coreflux) should have this problem. It depends if you think it's worth fixing or just instructing people to do what I did and erase directories manually.
