### ISSUE TITLE
How to remove a Hub access from the list?

### ISSUE THREAD

**Issue by HugoFelgueirasCF** [CorefluxCommunity/Coreflux-hub#2]
### Describe the bug 🐞

I added the connection to the same broker multiple times and with different names, but now I want to remove one of them from the list and I can't.

![Broker](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/dbbc25e1-7b16-4b47-baa6-3d13afbd7dac)

### Steps to Reproduce 🔄

1. Go to Home
![Home](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/48e28a61-a0c7-4b47-a4ad-06bcd60a86d9)

2. Click on Access Data Hub.
3. Fill the form pointing to the specific address.

![Connect](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/575c595b-deca-467f-9560-22a5269abe75)

5. You can repeat this any number of times and add the connections to your list. That will show in the Hub Access the added machines

![Broker](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/b2e2b3fd-faf9-4dc9-85b9-e1429b6751ad)

6. There is no way to remove these machines from the list.

### Expected behavior ✅

A simple button to remove the connected machines from the list.

### Environment 🌐

Ubuntu 22.04 LTS (Jammy Jellyfish)

### Terms of Service

- [X] I agree

**Comment by Jogana3** [comment]
Hi, it's not possible to delete an access yet, but it will be added in an update.

**Comment by HugoAVaz** [comment]
A feature was created in the roadmap.
https://github.com/CorefluxCommunity/Coreflux-roadmap/issues/12#issue-1985546788

It will be closed once feature is released

**Comment by HugoAVaz** [comment]
Done in version 1.2.008
