### ISSUE TITLE
Remote Data Hub Connection Status

### ISSUE THREAD

**Issue by HugoFelgueirasCF** [CorefluxCommunity/Coreflux-hub#3]
### Describe the bug 🐞

The status of the remote connection to one of my Data hub is showing offline even when I'm connected to it.

![Hub connection Status](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/087d7edf-82c2-4ad5-aa05-9a371b2b114f)

### Steps to Reproduce 🔄

1. I opened the Coreflux Hub and connected to the Remote Data Hub.
2. I changed the configuration of that Hub and restarted the service
3. I closed the Coreflux Hub on my local machine
4. Opened the Coreflux Hub on my local machine and connected to the Remote Hub
5. In the Hub it shows on the Top Bar the Connection green but in Hub Access list it shows Grey status and the description is Offline

### Expected behavior ✅

After I reconnect to the remote Hub with success I expected that the Status would show Green and Online

### Environment 🌐

Windows 11

### Terms of Service

- [X] I agree

**Comment by Jogana3** [comment]
This was due to a conflict with brokers that has Anonymous Login, will be fixed in version 1.2.006.
