### ISSUE TITLE
When opening the Hub config it's showing a strange screen

### ISSUE THREAD

**Issue by HugoFelgueirasCF** [CorefluxCommunity/Coreflux-hub#4]
### Describe the bug 🐞

I placed my laptop in hibernation and when I started it again I tried to change the Hub Config and this screen appeared

![Issue2](https://github.com/CorefluxCommunity/Coreflux-hub/assets/150243921/5d0c536a-c65e-4387-9584-49bb1dc38021)

I restarted the Coreflux hub and now it's working properly.

### Steps to Reproduce 🔄

1. With the Coreflux Hub opened change the configuration of the Data Hub you are working on.
2. Hibernate your computer.
3. Try to open the configuration again

### Expected behavior ✅

I was expecting that the Data hub configuration screen would show normally. 

### Environment 🌐

Windows 11

### Terms of Service

- [X] I agree

**Comment by Jogana3** [comment]
Hi Hugo, this happened because of a issue with a configuration in the code, will be fixed in version 1.2.006
